import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "../../components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="light"
          >
          <NavBar />
        <div className="container mx-auto">
          <main >{children}</main>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
